// <auto-generated />
namespace PRCS1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Blood_bank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Blood_bank));
        
        string IMigrationMetadata.Id
        {
            get { return "201612281404159_Blood_bank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
